# Generated by Django 4.1.5 on 2023-02-01 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaming_products', '0005_alter_product_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
