# Generated by Django 4.1.5 on 2023-02-01 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaming_products', '0006_remove_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='description',
        ),
    ]
