# Generated by Django 4.1.5 on 2023-02-01 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gaming_products', '0009_alter_product_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaming_products.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaming_products.product')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaming_products.subcategory')),
            ],
        ),
    ]
