# Generated by Django 4.1.5 on 2023-02-01 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gaming_products', '0011_alter_product_category_alter_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='allmodels',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
