# Generated by Django 4.1.5 on 2023-02-01 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gaming_products', '0012_allmodels_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allmodels',
            name='subcategory',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gaming_products.subcategory'),
        ),
    ]
