# Generated by Django 4.1.5 on 2023-02-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming_products', '0015_alter_allmodels_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='allmodels',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
