# Generated by Django 4.1.7 on 2023-02-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_checkoutcart_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutcart',
            name='shipping',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutcart',
            name='sub_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
